/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanasFormulario;

/**
 *
 * @author PERSONAL
 */
public class frmPedido extends javax.swing.JFrame {

    /**
     * Creates new form frmPedido
     */
    public frmPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_all = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        pnel_inf = new javax.swing.JPanel();
        text_dni = new javax.swing.JTextField();
        lblProveedor = new javax.swing.JLabel();
        lbldir = new javax.swing.JLabel();
        text_cliente = new javax.swing.JTextField();
        text_Direccion = new javax.swing.JTextField();
        lblus = new javax.swing.JLabel();
        text_telf = new javax.swing.JTextField();
        btn_bus_cli = new javax.swing.JButton();
        lbltelf = new javax.swing.JLabel();
        lblProveedor1 = new javax.swing.JLabel();
        text_cod = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btn_clean = new javax.swing.JButton();
        pnl_inf1 = new javax.swing.JPanel();
        lblprod = new javax.swing.JLabel();
        text_producto = new javax.swing.JTextField();
        lblcodprod = new javax.swing.JLabel();
        text_cod_pro = new javax.swing.JTextField();
        lblprecio1 = new javax.swing.JLabel();
        text_precio = new javax.swing.JTextField();
        lblstok1 = new javax.swing.JLabel();
        text_stok = new javax.swing.JTextField();
        lblcantidad1 = new javax.swing.JLabel();
        text_cant1 = new javax.swing.JTextField();
        btn_bus_prod = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_fac = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        pnl_cab = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_all.setBackground(new java.awt.Color(255, 255, 255));
        panel_all.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_all.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 120, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quitar.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        panel_all.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 90, 60));

        pnel_inf.setBackground(new java.awt.Color(255, 255, 255));
        pnel_inf.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnel_inf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_dni.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_dni.setEnabled(false);
        pnel_inf.add(text_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 300, -1));

        lblProveedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblProveedor.setText("Código:");
        pnel_inf.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        lbldir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbldir.setText("Razon Social:");
        pnel_inf.add(lbldir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        text_cliente.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_cliente.setEnabled(false);
        text_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_clienteActionPerformed(evt);
            }
        });
        pnel_inf.add(text_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 420, -1));

        text_Direccion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_Direccion.setEnabled(false);
        pnel_inf.add(text_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 520, -1));

        lblus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblus.setText("Dirección:");
        pnel_inf.add(lblus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        text_telf.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_telf.setEnabled(false);
        pnel_inf.add(text_telf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 190, -1));

        btn_bus_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Search.png"))); // NOI18N
        btn_bus_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bus_cliActionPerformed(evt);
            }
        });
        pnel_inf.add(btn_bus_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 90, 80));

        lbltelf.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbltelf.setText("Teléfono:");
        pnel_inf.add(lbltelf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        lblProveedor1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblProveedor1.setText("RUC");
        pnel_inf.add(lblProveedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 20));

        text_cod.setEnabled(false);
        text_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_codActionPerformed(evt);
            }
        });
        pnel_inf.add(text_cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 70, -1));

        panel_all.add(pnel_inf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 630, 130));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/añadir.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel_all.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 90, 70));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);
        jToolBar1.setEnabled(false);

        btn_clean.setBackground(new java.awt.Color(51, 153, 255));
        btn_clean.setForeground(new java.awt.Color(255, 255, 255));
        btn_clean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar3.png"))); // NOI18N
        btn_clean.setText("Reiniciar");
        btn_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cleanActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_clean);

        panel_all.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 30, 630, 40));

        pnl_inf1.setBackground(new java.awt.Color(255, 255, 255));
        pnl_inf1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2));
        pnl_inf1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblprod.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblprod.setText("Producto:");
        pnl_inf1.add(lblprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 20));

        text_producto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_producto.setEnabled(false);
        pnl_inf1.add(text_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 320, -1));

        lblcodprod.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblcodprod.setText("Código:");
        pnl_inf1.add(lblcodprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        text_cod_pro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_cod_pro.setEnabled(false);
        pnl_inf1.add(text_cod_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 10, 50, -1));

        lblprecio1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblprecio1.setText("Precio:");
        pnl_inf1.add(lblprecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        text_precio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_precio.setEnabled(false);
        pnl_inf1.add(text_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 50, -1));

        lblstok1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblstok1.setText("Stok:");
        pnl_inf1.add(lblstok1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 30, 20));

        text_stok.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_stok.setEnabled(false);
        pnl_inf1.add(text_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 70, -1));

        lblcantidad1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblcantidad1.setText("Cantidad:");
        pnl_inf1.add(lblcantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 60, 20));

        text_cant1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_cant1KeyReleased(evt);
            }
        });
        pnl_inf1.add(text_cant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 50, -1));

        panel_all.add(pnl_inf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 540, 80));

        btn_bus_prod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar_prod.png"))); // NOI18N
        btn_bus_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bus_prodActionPerformed(evt);
            }
        });
        panel_all.add(btn_bus_prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 90, 80));

        table_fac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_fac);

        panel_all.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 540, 130));

        btn_agregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar01.png"))); // NOI18N
        btn_agregar.setText(" Guardar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        panel_all.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 120, 30));

        pnl_cab.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pedidos");

        javax.swing.GroupLayout pnl_cabLayout = new javax.swing.GroupLayout(pnl_cab);
        pnl_cab.setLayout(pnl_cabLayout);
        pnl_cabLayout.setHorizontalGroup(
            pnl_cabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(576, Short.MAX_VALUE))
        );
        pnl_cabLayout.setVerticalGroup(
            pnl_cabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_all.add(pnl_cab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        getContentPane().add(panel_all, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
//        eliminarventa();
//        cargarVenta();
//        cargarDetalle2();
//        //suma();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void text_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_clienteActionPerformed

    private void btn_bus_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bus_cliActionPerformed
        // TODO add your handling code here:
        //new JDialogVer_cli(this, false).setVisible(true);
    }//GEN-LAST:event_btn_bus_cliActionPerformed

    private void text_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_codActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

//        insertVenta();
//        text_stok.setText("");
//        //cantporPre();
//        cargarVenta();
//        cargarDetalle2();
//        //suma();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cleanActionPerformed
        // TODO add your handling code here:
        //reiniciar();
    }//GEN-LAST:event_btn_cleanActionPerformed

    private void text_cant1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_cant1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cant1KeyReleased

    private void btn_bus_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bus_prodActionPerformed
        // TODO add your handling code here:
       // new JDialogVerProductos(this, false).setVisible(true);
    }//GEN-LAST:event_btn_bus_prodActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
//        limpiar();
//
//        text_dni.setText("");
//        text_cliente.setText("");
//        text_Correo.setText("");
//        text_telf.setText("");
//        text_Direccion.setText("");
//        text_subtotal.setText("");
//        text_iva.setText("");
//        text_total.setText("");
//        text_stok.setText("");
//        if(jRadioButtonBoleta.isSelected()){
//            actualizarDatos();
//        }else if(jRadioButtonFactura.isSelected()){
//            actualizarDatos2();
//        }
//        limpiarTabla();
//        text_cod.setText("");
//        insertVerVenta();
//        new JDialogVer_Venta(this, false).setVisible(true);
    }//GEN-LAST:event_btn_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_bus_cli;
    private javax.swing.JButton btn_bus_prod;
    private javax.swing.JButton btn_clean;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblProveedor1;
    private javax.swing.JLabel lblcantidad1;
    private javax.swing.JLabel lblcodprod;
    private javax.swing.JLabel lbldir;
    private javax.swing.JLabel lblprecio1;
    private javax.swing.JLabel lblprod;
    private javax.swing.JLabel lblstok1;
    private javax.swing.JLabel lbltelf;
    private javax.swing.JLabel lblus;
    private javax.swing.JPanel panel_all;
    private javax.swing.JPanel pnel_inf;
    private javax.swing.JPanel pnl_cab;
    private javax.swing.JPanel pnl_inf1;
    private javax.swing.JTable table_fac;
    public static javax.swing.JTextField text_Direccion;
    private javax.swing.JTextField text_cant1;
    public static javax.swing.JTextField text_cliente;
    public static javax.swing.JTextField text_cod;
    public static javax.swing.JTextField text_cod_pro;
    public static javax.swing.JTextField text_dni;
    public static javax.swing.JTextField text_precio;
    public static javax.swing.JTextField text_producto;
    public static javax.swing.JTextField text_stok;
    public static javax.swing.JTextField text_telf;
    // End of variables declaration//GEN-END:variables
}
